server:
  port: 8080

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  datasource:
    name: 421
    url: jdbc:mysql://127.0.0.1:3306/421?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: com.example.springboot.entity  # 注意：对应实体类的路径  classpath:mybaties/*.xml mybaties 表格要缩进，否则读取不到
  mapper-locations: classpath:mybaties/*.xml    #注意：一定要对应mapper映射xml文件的所在路径 classpath:com.example.springboot.mybaties/*.xml

