server:
  port: 17881
redis:
  host: localhost
  port: 6379
  pass:
  default.db: 5
  timeout: 10000
  maxTotal: 1024
  maxIdle: 100
  maxWaitMillis: 1000
  testOnBorrow: true
  #默认过期时间，0-无限期，单位小时
  #有效时间为24小时
  defaultExpiration: 24

mybatis:
  mapperLocations: classpath*:com/yb/*/mapper/*.xml
  config-location: classpath:mybatis.xml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tp_loan?useSSL=false&characterEncoding=UTF-8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

swagger.show: true